import { Command } from 'commander';
import chalk from 'chalk';
import express from 'express';
import fs from 'node:fs';

interface MockOptions {
  response?: string;
  status?: number;
  port?: number;
  delay?: number;
  method?: string;
}

export function registerMockCommands(program: Command): void {
  program
    .command('mock')
    .argument('<route>', 'Route pattern, e.g. /users/:id')
    .description('Spin up a lightweight mock server for rapid prototyping')
    .option('--response <path>', 'Path to JSON response file')
    .option('--status <code>', 'HTTP status code', (value) => Number(value), 200)
    .option('--port <port>', 'Port to listen on', (value) => Number(value), 4000)
    .option('--delay <ms>', 'Artificial delay in milliseconds', (value) => Number(value), 0)
    .option('--method <method>', 'HTTP method to respond to', 'ALL')
    .action(async (route: string, options: MockOptions) => {
      const app = express();
      app.use(express.json());
      const responder = (req: express.Request, res: express.Response) => {
        if (options.delay) {
          setTimeout(() => respond(req, res, route, options), options.delay);
        } else {
          respond(req, res, route, options);
        }
      };
      const method = options.method?.toUpperCase() ?? 'ALL';
      const expressMethod = method === 'ALL' ? 'all' : method.toLowerCase();
      if (!(expressMethod in app)) {
        console.log(chalk.red(`Unsupported HTTP method: ${method}`));
        return;
      }
      (app as any)[expressMethod](route, responder);
      app.listen(options.port ?? 4000, () => {
        console.log(
          chalk.green(
            `Mock server ready on http://localhost:${options.port ?? 4000}${route} (${method} → ${options.status ?? 200})`
          )
        );
      });
    });
}

function respond(req: express.Request, res: express.Response, route: string, options: MockOptions) {
  if (options.response) {
    try {
      const data = fs.readFileSync(options.response, 'utf8');
      res.status(options.status ?? 200).json(JSON.parse(data));
      return;
    } catch (error) {
      console.log(chalk.red(`Failed to read response file: ${(error as Error).message}`));
      res.status(500).json({ error: 'Invalid mock response file' });
      return;
    }
  }
  res.status(options.status ?? 200).json({
    route,
    method: req.method,
    message: 'Mock response generated by Squirrel API Studio CLI',
    params: req.params,
    body: req.body,
  });
}
