nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.3.cjs
httpTimeout: 300000
npmRegistryServer: "https://registry.npmjs.org"
httpProxy: "http://192.168.43.1:8080"
httpsProxy: "http://192.168.43.1:8080"
networkConcurrency: 1
httpRetry: 5
